// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbbCnDitFrLj0bqc0FJfjKRGp6Oiswkk',
    appId: '1:739459395370:web:ff4a28cc9f0ef2368af853',
    messagingSenderId: '739459395370',
    projectId: 'themeapp-15b45',
    authDomain: 'themeapp-15b45.firebaseapp.com',
    storageBucket: 'themeapp-15b45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDru_UXJ9OzWwmN_1M24gHFEGSsrmB69GM',
    appId: '1:739459395370:android:ce400116d268a2fc8af853',
    messagingSenderId: '739459395370',
    projectId: 'themeapp-15b45',
    storageBucket: 'themeapp-15b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVk5hvKlv79KkUc5bJkbCZr7WrVwoqG8',
    appId: '1:739459395370:ios:d20f5a6274739fb68af853',
    messagingSenderId: '739459395370',
    projectId: 'themeapp-15b45',
    storageBucket: 'themeapp-15b45.firebasestorage.app',
    iosBundleId: 'com.example.themeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVk5hvKlv79KkUc5bJkbCZr7WrVwoqG8',
    appId: '1:739459395370:ios:d20f5a6274739fb68af853',
    messagingSenderId: '739459395370',
    projectId: 'themeapp-15b45',
    storageBucket: 'themeapp-15b45.firebasestorage.app',
    iosBundleId: 'com.example.themeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEbbCnDitFrLj0bqc0FJfjKRGp6Oiswkk',
    appId: '1:739459395370:web:aed949b2ddde190e8af853',
    messagingSenderId: '739459395370',
    projectId: 'themeapp-15b45',
    authDomain: 'themeapp-15b45.firebaseapp.com',
    storageBucket: 'themeapp-15b45.firebasestorage.app',
  );
}
